### ISSUE TITLE
Building required plotly - Dependency fail

### ISSUE THREAD

**Issue by gustavjoh** [sfilges/umiAnalyzer#28]
![image](https://user-images.githubusercontent.com/33893359/143047983-be34ab47-3658-4517-912f-589264ab40f7.png)

But it is listed in Imports in the description file so don't know where the error is...

**Comment by sfilges** [comment]
I've been installing it on clean versions of Windows, MacOS and Ubuntu today and didn't have that issue, including installation on R devel. 

Have you tried to install with this?

`devtools::install_github("sfilges/umiAnalyzer")`
