### ISSUE TITLE
App crash when loading folder with no data

### ISSUE THREAD

**Issue by gustavjoh** [sfilges/umiAnalyzer#29]
![image](https://user-images.githubusercontent.com/33893359/143057715-d0163a95-6d97-4223-b9b8-17679ec605eb.png)

If the user click the option and then choose a directory and chooses a directory with no or incomplete samples the UI crashes

**Comment by sfilges** [comment]
This should now be fixed with pull request #30. Please try installing again from master.

**Comment by sfilges** [comment]
Closed, see comment above.
